# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: emheuga <emheuga@student.42angouleme.fr>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created:  Tue May 15 15:44:4 by emheuga           #+#    #+#              #
#    Updated: 2026/05/04 12:28:31 by emheuga          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


all	: do_configure

do_configure	:
	./configure

clean	:
	./configure clean

re	: clean all
